Controllers/AppRolesController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace AgenziaSpedizioni.Controllers
{
	[Authorize (Roles = "SuperAdmin")]
	public class AppRolesController : Controller
    {
		private readonly RoleManager<IdentityRole> _roleManager;

		public AppRolesController(RoleManager<IdentityRole> roleManager) {

			_roleManager = roleManager;
		}


		public IActionResult Index()
		{
			var roles = _roleManager.Roles;
			return View(roles);

		}

        public IActionResult Create()
        {
            return View();
        }


        
        public async Task<IActionResult> Delete(string id)
        {
			var x = _roleManager.Roles.FirstOrDefault(x => x.Id == id);
			await _roleManager.DeleteAsync(x);


            return RedirectToAction("Index");
        }



        [HttpPost]
		public async  Task<IActionResult> Create(IdentityRole model )
		{
			if (!_roleManager.RoleExistsAsync(model.Name).GetAwaiter().GetResult())
			{
				_roleManager.CreateAsync(new IdentityRole(model.Name)).GetAwaiter().GetResult();

			}

			return RedirectToAction("Index");
		}

      




    }
}

Controllers/CustomerController.cs
using System;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using Microsoft.EntityFrameworkCore;
using AgenziaSpedizioni.Data;
using AgenziaSpedizioni.Models;

namespace AgenziaSpedizioni.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CustomerController : Controller
    {
        private Data.ApplicationDbContext _db;
        public CustomerController(Data.ApplicationDbContext context)
        {
            _db = context;

        }

        public IActionResult Index()
        {
           var model = _db.Users.ToList();
            return View(model);

        }

        public IActionResult AddCustomer()
        {
            User model = new User();
            return View(model);
        }

        [HttpPost]
        public IActionResult AddCustomer(User model)
        {
            _db.Users.Add(model);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult EditCustomer(int id)
        {
            var model = _db.Users.FirstOrDefault(x => x.Id.Equals(id));
            return View(model);
        }

        [HttpPost]
        public IActionResult EditCustomerPost(User model, int id)
        {
            var user = _db.Users.FirstOrDefault(x => x.Id.Equals(id));
            user.Name = model.Name;
            user.Surname = model.Surname;
            user.Number = model.Number;
            user.Address = model.Address;
            user.City = model.City;
            user.Country = model.Country;
            user.Postal_Code = model.Postal_Code;
            user.Customer_Type = model.Customer_Type;
            user.CF = model.CF;
            user.Vat = model.Vat;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult DeleteCustomer(int id)
        {
            try
            {
                var customer = _db.Users.FirstOrDefault(x => x.Id.Equals(id));

            if (customer.Shipments.Any())
            {
                foreach (var ship in customer.Shipments)
                {
                    _db.Shipments.FirstOrDefault(x => x.Traking.Equals(ship)).user = "USER DELETED";
                    
                }
            }
            _db.Users.Remove(customer);
            _db.SaveChanges();

            }
            catch (Exception e) { return RedirectToAction("Index"); }
            return RedirectToAction("Index");
        }

    }
}

Controllers/TrackingController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using AgenziaSpedizioni.Models;

namespace AgenziaSpedizioni.Controllers
{

    public class TrackingController : Controller
    {

        private Data.ApplicationDbContext _db;
        public TrackingController(Data.ApplicationDbContext context)
        {
            _db = context;

        }

        public IActionResult Index()
        {

            return View();
        }

        [HttpPost]
        public IActionResult Index(string search)
        {
            if(search != "" && search != null) { 
            var tracking = _db.Shipments.FirstOrDefault(x => x.Traking.Equals(search));
            var cf = _db.Users.FirstOrDefault(x => x.CF.Equals(search));
            var vat = _db.Users.FirstOrDefault(x => x.Vat.Equals(search));


            if (tracking != null)
            {
                return RedirectToAction("TrackingStatus",new { tracking = tracking.Traking} );
            }
            else if(cf != null)
            {
                var model = new List<Shipment>();
                foreach (var ship in cf.Shipments)
                {
                    model.Add(_db.Shipments.FirstOrDefault(x => x.Traking.Equals(ship)));
                }

                return View("MultiTracking", model);

            }
            else if (vat != null)
            {
                var model = new List<Shipment>();

                foreach (var ship in vat.Shipments)
                {
                    model.Add(_db.Shipments.FirstOrDefault(x => x.Traking.Equals(ship)));
                }

                return View("MultiTracking", model);
            }
            }
            return View();

        }

        public IActionResult MultiTracking(List<Shipment> list)
        {

            return View(list);
        }

        public IActionResult TrackingStatus(string tracking) {

            var model = _db.Shipments.FirstOrDefault(x => x.Traking.Equals(tracking));

            return View(model);
        }




    }

        
}

Controllers/UserController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using AgenziaSpedizioni.Models;

namespace AgenziaSpedizioni.Controllers
{
    [Authorize(Roles = "SuperAdmin")]
    public class UserController : Controller
    {
        private readonly UserManager<IdentityUser> _user;
        private readonly RoleManager<IdentityRole> _role;

        public UserController(UserManager<IdentityUser> user, RoleManager<IdentityRole> role) {

            _user = user;
            _role = role;
        }


        public IActionResult Index()
        {
            var user = _user.Users;
            return View(user);

        }
 

        public IActionResult EditUser(string id)
        {
            var user = _user.Users.FirstOrDefault(x => x.Id == id);
       
            return View(user);
        }

       
        [HttpPost]
        public async Task<IActionResult> EditUser(string id, string permission)
        {
            var user = _user.Users.FirstOrDefault(x => x.Id == id);
            await _user.AddToRoleAsync(user, permission);
            return RedirectToAction("EditUser", new { user.Id });
        }


        public async Task<IActionResult> DeleteUser(string id)
        {

            var user = _user.Users.FirstOrDefault(x => x.Id == id);
            await _user.DeleteAsync(user);

            return RedirectToAction("Index");
        }


        public async Task<IActionResult> RemoveRole(string role, string id)
        {

            var user = _user.Users.FirstOrDefault(x => x.Id == id);
            await _user.RemoveFromRoleAsync(user, role);

            return RedirectToAction("EditUser" ,new { id });
        }
    }



    
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@inject RoleManager<IdentityRole> role

@{
    ViewData["Title"] = "Express";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AgenziaSpedizioni.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@ViewData["Title"]</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User) && (await UserManager.IsInRoleAsync(UserManager.Users.FirstOrDefault(x => x.Id == UserManager.GetUserId(User)), "Admin") || await UserManager.IsInRoleAsync(UserManager.Users.FirstOrDefault(x => x.Id == UserManager.GetUserId(User)), "SuperAdmin")))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Customers</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Shipments" asp-action="Index">Shipments</a>
                            </li>

                        }

                        <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Tracking" asp-action="Index">Tracking</a>
                        </li>
                    </ul>
                    @if (SignInManager.IsSignedIn(User) && await UserManager.IsInRoleAsync(UserManager.Users.FirstOrDefault(x => x.Id == UserManager.GetUserId(User)), "SuperAdmin"))
                    {
                       <ul class="navbar-nav">
                           <li class="nav-item">
                               <a class="nav-link text-dark" asp-area="" asp-controller="AppRoles" asp-action="Index">Permission</a>
                           </li>
                           <li class="nav-item">
                               <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                           </li>
                       </ul>
                    }
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Express 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>